//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_Operations.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Employee
    {
        public int EmpID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Gender { get; set; }
        public bool MaritalStatus { get; set; }
        public System.DateTime DOB { get; set; }
        public string Hobbies { get; set; }
        public string EmployeePhoto { get; set; }
        public decimal Salary { get; set; }
        public string Address { get; set; }
        public int CountryID { get; set; }
        public int StateID { get; set; }
        public int CityID { get; set; }
        public string ZipCode { get; set; }
        public string Password { get; set; }
    
        public virtual TBL_City TBL_City { get; set; }
        public virtual TBL_Country TBL_Country { get; set; }
        public virtual TBL_State TBL_State { get; set; }
    }
}
